apiVersion: apps/v1
kind: Deployment
metadata:
  name: {servicename}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {servicename}
  template:
    metadata:
      labels:
        app: {servicename}
    spec:
      containers:
      - name: inventorydbservice
        image: {imagename}
        ports:
        - containerPort: 80
        env:        
        - name: {connectionstringname}
          value: '{connectionstring}'
        